export const games = [
  {
    game: "Clank!",
    players: "2-4",
    difficulty: "Medium",
    playTime: 60,
    link: "https://boardgamegeek.com/boardgame/201808/clank-deck-building-adventure",
  },
  {
    game: "7 Wonders",
    players: "3-7",
    difficulty: "Easy",
    playTime: 30,
    link: "https://boardgamegeek.com/boardgame/68448/7-wonders",
  },
  {
    game: "Nemesis",
    players: "1-5",
    difficulty: "High",
    playTime: 90,
    link: "https://boardgamegeek.com/boardgame/167355/nemesis",
  },
  {
    game: "Sheriff of Nottingham",
    players: "3-5",
    difficulty: "Moderate to high",
    playTime: 60,
    link: "https://boardgamegeek.com/boardgame/157969/sheriff-nottingham",
  },
  {
    game: "7 Wonders Architects",
    players: "2-7",
    difficulty: "Easy",
    playTime: 25,
    link: "https://boardgamegeek.com/boardgame/329491/7-wonders-architects",
  },
  {
    game: "Takenoko",
    players: "2-4",
    difficulty: "Easy to medium",
    playTime: 45,
    link: "https://boardgamegeek.com/boardgame/70919/takenoko",
  },
  {
    game: "Flamecraft",
    players: "2-4",
    difficulty: "Medium to high",
    playTime: 60,
    link: "https://boardgamegeek.com/boardgame/315746/flamecraft",
  },
  {
    game: "El Dorado",
    players: "2-4",
    difficulty: "Easy to medium",
    playTime: 60,
    link: "https://boardgamegeek.com/boardgame/216132/el-dorado",
  },
  {
    game: "Hues and Cues",
    players: "3-10",
    difficulty: "Easy to medium",
    playTime: 30,
    link: "https://boardgamegeek.com/boardgame/281259/hues-and-cues",
  },
  {
    game: "Splendor",
    players: "2-4",
    difficulty: "Easy",
    playTime: "30",
    link: "https://boardgamegeek.com/boardgame/148228/splendor",
  },
  {
    game: "Chameleon",
    players: "3-8",
    difficulty: "Easy",
    playTime: "20",
    link: "https://boardgamegeek.com/boardgame/182847/chameleon",
  },
  {
    game: "Risk",
    players: "2-6",
    difficulty: "Medium to high",
    playTime: "120",
    link: "https://boardgamegeek.com/boardgame/181/risk",
  },
  {
    game: "Axis and Allies",
    players: "2-5",
    difficulty: "High",
    playTime: "240",
    link: "https://boardgamegeek.com/boardgame/98/axis-allies",
  },
  {
    game: "Settlers of Catan",
    players: "3-4",
    difficulty: "Easy to medium",
    playTime: "90",
    link: "https://boardgamegeek.com/boardgame/13/catan",
  },
  {
    game: "Tsuro",
    players: "2-8",
    difficulty: "Easy to medium",
    playTime: "15",
    link: "https://boardgamegeek.com/boardgame/16992/tsuro",
  },
  {
    game: "Lords of Waterdeep",
    players: "2-5",
    difficulty: "Medium to high",
    playTime: "120",
    link: "https://boardgamegeek.com/boardgame/110327/lords-waterdeep",
  },

  {
    game: "7 Wonders Duel",
    players: "2",
    difficulty: "Medium",
    playTime: "30",
    link: "https://boardgamegeek.com/boardgame/173346/7-wonders-duel",
  },
  {
    game: "The Mind",
    players: "2-4",
    difficulty: "Easy",
    playTime: "15",
    link: "https://boardgamegeek.com/boardgame/244992/mind",
  },
  {
    game: "Exploding Kittens",
    players: "2-5",
    difficulty: "Easy",
    link: "https://boardgamegeek.com/boardgame/244992/mind",
  },
  {
    game: "Love Letter",
    players: "2-4",
    difficulty: "Easy",
    playTime: 20,
    link: "https://boardgamegeek.com/boardgame/129622/love-letter",
  },
  {
    game: "Sushi Go Party!",
    players: "2-8",
    difficulty: "Easy",
    playTime: 20,
    link: "https://boardgamegeek.com/boardgame/192291/sushi-go-party",
  },
  {
    game: "Codenames",
    players: "2-8+",
    difficulty: "Easy",
    playTime: 15,
    link: "https://boardgamegeek.com/boardgame/178900/codenames",
  },
  {
    game: "Skull",
    players: "3-6",
    difficulty: "Easy",
    playTime: 45,
    link: "https://boardgamegeek.com/boardgame/92415/skull",
  },
  {
    game: "The Crew",
    players: "3-5",
    difficulty: "Moderate",
    playTime: 20,
    link: "https://boardgamegeek.com/boardgame/284083/crew-quest-planet-nine",
  },
  {
    game: "Canvas",
    players: "2-5",
    difficulty: "Moderate",
    playTime: 30,
    link: "https://boardgamegeek.com/boardgame/290236/canvas",
  },
  {
    game: "Monikers",
    players: "4+",
    difficulty: "Easy",
    playTime: 60,
    link: "https://boardgamegeek.com/boardgame/156546/monikers",
  },
  {
    game: "Chess",
    players: "2",
    difficulty: "Moderate",
    playTime: "30-180",
    link: "https://boardgamegeek.com/boardgame/171/chess",
  },
  {
    game: "Scrabble",
    players: "2-4",
    difficulty: "Moderate",
    playTime: "90",
    link: "https://boardgamegeek.com/boardgame/320/scrabble",
  },
];
